In [1]:
import numpy as np
import cv2
import math
import sys

In [18]:
def resize_shrink(matrix, fx, fy):
    """
    Purpose:
        resize a matrix given fx and fy.
    Input:
        fx: resize on column
        fy: resize on row
    Output:
        Resized matrix list
    """
    
    fx_inv = int(1 / fx)
    fy_inv = int(1 / fy)
    res = []
    
    for i in range(0, len(matrix), fy_inv):
        res_row = []
        for j in range(0, len(matrix[i]), fx_inv):
            res_row.append(matrix[i][j])
        res.append(res_row)
    
    return res

In [21]:
img = cv2.imread("../task2_img/task2.jpg", 0)
img2 = np.asarray(resize_shrink(img, 1/2, 1/2))
img4 = np.asarray(resize_shrink(img, 1/4, 1/4))
img8 = np.asarray(resize_shrink(img, 1/8, 1/8))

In [23]:
cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.imshow('img',  img)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.namedWindow('img2', cv2.WINDOW_NORMAL)
cv2.imshow('img2', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.namedWindow('img4', cv2.WINDOW_NORMAL)
cv2.imshow('img4', img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.namedWindow('img4', cv2.WINDOW_NORMAL)
cv2.imshow('img4', img8)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [8]:
t1 = np.arange(100).reshape(10,10)

In [11]:
np.asarray(resize(t1,1/2,1/2))

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [12]:
t1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
t2 = np.arange(81).reshape(9,9)

In [14]:
np.asarray(resize(t2,1/2,1/2))

array([[ 0,  2,  4,  6,  8],
       [18, 20, 22, 24, 26],
       [36, 38, 40, 42, 44],
       [54, 56, 58, 60, 62],
       [72, 74, 76, 78, 80]])

In [15]:
t2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])